// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA03C68G_sb_TXBZXsPZeYiuo2AVOi-io',
    appId: '1:802205455678:web:cd867cfaa1153167a6486f',
    messagingSenderId: '802205455678',
    projectId: 'tfcm-e2830',
    authDomain: 'tfcm-e2830.firebaseapp.com',
    storageBucket: 'tfcm-e2830.firebasestorage.app',
    measurementId: 'G-V2HXVDS2DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRq5zK4Zuk492zEdMPIE1_mRhpRjWNgHg',
    appId: '1:802205455678:android:d060cc7f4f85ab31a6486f',
    messagingSenderId: '802205455678',
    projectId: 'tfcm-e2830',
    storageBucket: 'tfcm-e2830.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEicXnurEKXGVfRzpUjcP4DDSH0Pu8Irw',
    appId: '1:802205455678:ios:48119b8ef3c23045a6486f',
    messagingSenderId: '802205455678',
    projectId: 'tfcm-e2830',
    storageBucket: 'tfcm-e2830.firebasestorage.app',
    iosBundleId: 'com.example.tfcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEicXnurEKXGVfRzpUjcP4DDSH0Pu8Irw',
    appId: '1:802205455678:ios:48119b8ef3c23045a6486f',
    messagingSenderId: '802205455678',
    projectId: 'tfcm-e2830',
    storageBucket: 'tfcm-e2830.firebasestorage.app',
    iosBundleId: 'com.example.tfcm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA03C68G_sb_TXBZXsPZeYiuo2AVOi-io',
    appId: '1:802205455678:web:dce0fb07b1b0ad8ca6486f',
    messagingSenderId: '802205455678',
    projectId: 'tfcm-e2830',
    authDomain: 'tfcm-e2830.firebaseapp.com',
    storageBucket: 'tfcm-e2830.firebasestorage.app',
    measurementId: 'G-BQW850N04F',
  );
}
